### ISSUE TITLE
Add Sneha's picture to Bay Area team

### ISSUE THREAD

**Issue by amy236** [dsoglobal/dsowebsite#17]
I'm not able to find Sneha's picture in the dropdown here: https://dsowebsite-179d5.netlify.app/admin/#/collections/people/entries/bay. Even though she is added an individual team member with her picture already.

**Comment by ajbuchanjr** [comment]
Picture is available if search "Snehna" in drop down is used. By default, drop down only displays 20 options. Changed default to 1000 so everyone should appear.
