### ISSUE TITLE
Make pictures of individual team members smaller 

### ISSUE THREAD

**Issue by amy236** [dsoglobal/dsowebsite#18]
The pictures on team members' individual pages are still coming up huge on my screen.
Make 1/3 the current size?

Screenshot attached.
![Screen Shot 2020-05-27 at 7 40 04 PM](https://user-images.githubusercontent.com/54003392/83092310-e3087980-a051-11ea-85ab-77c46353d02a.png)

**Comment by ajbuchanjr** [comment]
Adjusted. Problem is the same template for people posts is used for individual project page pictures so those will also be smaller. Will leave issue open until confirmation.

**Comment by ajbuchanjr** [comment]
Images adjusted
