### ISSUE TITLE
Update profile on Team page

### ISSUE THREAD

**Issue by gina406** [dsoglobal/dsowebsite#20]
I was able to update my picture/info on my individual profile page; yet, it seems like the Team page is not updated. 
![Screenshot 2021-03-26 141146](https://user-images.githubusercontent.com/81531432/112764843-34113300-8fbf-11eb-89aa-f06a24371995.jpg)

**Comment by ajbuchanjr** [comment]
After changing individual team member pages title or picture you have to go to the Individual Teams page and update the title and picture fields to force the update by searching and picking name again. I updated your page and also updated the DSO Website Instructions to note this information that was missing. Thanks for reporting the issue so we could clear this up!

![UpdatedInfo](https://user-images.githubusercontent.com/77211/112768187-5ebfb380-8fe0-11eb-8f51-6ddcfacfd57d.PNG)
